services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Dune_sqlserver
    environment:
      SA_PASSWORD: "e4b27SD-98"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'e4b27SD-98' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Dune-backend
    ports:
      - "7050:7050"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Dune: "Server=sqlserver;Database=Dune;User Id=sa;Password=e4b27SD-98;Encrypt=false;TrustServerCertificate=true;"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
